### ISSUE TITLE
Add time flashcards (p 70)

### ISSUE THREAD

**Issue by alanreidt** [alanreidt/english-learning#2]
### Sources:
- [How to say the time in English – Examples and Reference | English Study Page](https://www.englisch-hilfen.de/en/words/uhr.htm),
- [Telling The Time in English | Englisch Hilfen](https://englishstudypage.com/grammar/telling-the-time-in-english/).

### Todo:
- [x] past and to
- [x] quarter and half
- [x] full hours
- [x] am and pm
